# Generated by Django 6.1 on 2026-08-26 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=30)),
                ('location_name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Poland', max_length=100)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('location_type', models.CharField(choices=[('BRANCH', 'Branch'), ('AIRPORT', 'Airport'), ('HOTEL_DELIVERY', 'Hotel delivery'), ('SEASONAL_POINT', 'Seasonal point'), ('CUSTOM_POINT', 'Custom point'), ('OTHER', 'Other')], default='BRANCH', max_length=20)),
                ('airport_code', models.CharField(blank=True, max_length=3)),
                ('supports_pickup', models.BooleanField(default=True)),
                ('supports_return', models.BooleanField(default=True)),
                ('supports_delivery', models.BooleanField(default=False)),
                ('supports_after_hours', models.BooleanField(default=False)),
                ('requires_prepayment', models.BooleanField(default=False)),
                ('default_pickup_instructions', models.TextField(blank=True)),
                ('default_return_instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('internal_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['supplier__supplier_name', 'location_name'],
                'constraints': [models.UniqueConstraint(fields=('supplier', 'location_code'), name='unique_location_code_per_supplier')],
            },
        ),
    ]
