# Generated by Django 6.1 on 2026-08-27 17:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_add_vehicle_groups_and_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extras', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['supplier__supplier_name', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierExtraRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_type', models.CharField(choices=[('FIXED', 'Fixed'), ('PER_DAY', 'Per day'), ('PER_RENTAL', 'Per rental'), ('PER_UNIT', 'Per unit'), ('PER_DRIVER_DAY', 'Per driver per day'), ('FORMULA', 'Formula')], max_length=20)),
                ('amount_gross', models.DecimalField(decimal_places=2, help_text='Final customer price including VAT.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('days_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('days_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('minimum_amount_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('maximum_amount_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('formula_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='suppliers.supplierextra')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extra_rates', to='suppliers.supplierlocation')),
            ],
            options={
                'ordering': ['extra', '-priority', '-valid_from'],
            },
        ),
        migrations.AddConstraint(
            model_name='supplierextra',
            constraint=models.UniqueConstraint(fields=('supplier', 'extra_code'), name='unique_extra_code_per_supplier'),
        ),
    ]
