# Generated by Django 6.1 on 2026-08-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_supplierextra_supplierextrarate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierextrarate',
            name='rate_code',
            field=models.CharField(default='DEFAULT', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='supplierextrarate',
            constraint=models.UniqueConstraint(fields=('extra', 'rate_code'), name='unique_rate_code_per_extra'),
        ),
    ]
