# Generated by Django 6.1 on 2026-08-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0009_supplierextrarate_rate_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierextra',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
