# Generated by Django 6.1 on 2026-08-27 18:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0010_supplierextra_is_mandatory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('version', models.CharField(max_length=50)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manual'), ('EXCEL', 'Excel')], default='MANUAL', max_length=20)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_lists', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['supplier__supplier_name', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='PriceDayRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_code', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=80)),
                ('days_from', models.PositiveSmallIntegerField()),
                ('days_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_ranges', to='suppliers.pricelist')),
            ],
            options={
                'ordering': ['sort_order', 'days_from'],
            },
        ),
        migrations.CreateModel(
            name='PriceSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_code', models.CharField(max_length=50)),
                ('season_name', models.CharField(max_length=120)),
                ('rental_date_from', models.DateField()),
                ('rental_date_to', models.DateField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='suppliers.pricelist')),
            ],
            options={
                'ordering': ['rental_date_from', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='VehicleRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_rate_gross', models.DecimalField(decimal_places=2, help_text='Daily customer price including VAT.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('day_range', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_rates', to='suppliers.pricedayrange')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_rates', to='suppliers.priceseason')),
                ('vehicle_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='suppliers.vehiclegroup')),
            ],
            options={
                'ordering': ['season', 'vehicle_group', 'day_range'],
            },
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(fields=('supplier', 'version'), name='unique_price_list_version_per_supplier'),
        ),
        migrations.AddConstraint(
            model_name='pricedayrange',
            constraint=models.UniqueConstraint(fields=('price_list', 'range_code'), name='unique_day_range_code_per_price_list'),
        ),
        migrations.AddConstraint(
            model_name='priceseason',
            constraint=models.UniqueConstraint(fields=('price_list', 'season_code'), name='unique_season_code_per_price_list'),
        ),
        migrations.AddConstraint(
            model_name='vehiclerate',
            constraint=models.UniqueConstraint(fields=('season', 'vehicle_group', 'day_range'), name='unique_vehicle_rate'),
        ),
    ]
