# Generated by Django 6.1 on 2026-09-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0021_supplier_regular_service_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='show_in_introduction',
            field=models.BooleanField(default=False, verbose_name='Показывать в представлении агентства'),
        ),
    ]
