# Generated by Django 6.1 on 2026-09-20 16:07

from django.db import migrations, models


def create_wording(apps, schema_editor):
    wording = apps.get_model('suppliers', 'AirportPickupWording')
    for code, text in (
        ('DESK', 'קבלת הרכב בדלפק חברת ההשכרה בשדה התעופה.'),
        ('MEET', 'נציג חברת ההשכרה יפגוש אתכם בשדה התעופה ויכוון אתכם לקבלת הרכב.'),
        ('UNKNOWN', 'מקום קבלת הרכב יתואם לפני ביצוע ההזמנה.'),
    ):
        wording.objects.get_or_create(method_code=code, defaults={'text_he': text})
    location = apps.get_model('suppliers', 'SupplierLocation')
    location.objects.filter(
        supplier__supplier_name='Kaizen Rent', airport_code='KTW', is_active=True,
    ).update(supports_terminal_delivery=True)


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0022_supplier_show_in_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportPickupWording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_code', models.CharField(max_length=20, unique=True)),
                ('text_he', models.CharField(max_length=250)),
            ],
        ),
        migrations.RunPython(create_wording, migrations.RunPython.noop),
    ]
