# Generated by Django 6.1 on 2026-09-23 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0023_airportpickupwording'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='audience',
            field=models.CharField(choices=[('STANDARD', 'Обычный клиент'), ('SUBAGENT', 'Клиент субагента')], default='STANDARD', max_length=20, verbose_name='Для кого ценник'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='subagent_markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Процент к общей сумме'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='subagent_pricing_method',
            field=models.CharField(choices=[('STANDARD', 'Обычный ценник'), ('DEDICATED', 'Отдельный ценник субагента'), ('PERCENT_TOTAL', 'Процент к общей сумме')], default='STANDARD', max_length=20, verbose_name='Расчёт для субагента'),
        ),
    ]
