# Generated by Django 6.1 on 2026-09-30 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0029_vehicle_group_customer_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('cross_border_required', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='vehiclegroup',
            name='show_in_offers',
            field=models.BooleanField(default=True, verbose_name='Предлагать в новых офертах'),
        ),
        migrations.CreateModel(
            name='CityServiceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.ForeignKey(blank=True, help_text='Пусто: обслуживание по обычным тарифам поставщика без отдельной городской доплаты.', null=True, on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplierextra')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_service_rules', to='suppliers.supplier')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_rules', to='suppliers.offercity')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('city', 'supplier'), name='unique_city_service_supplier')],
            },
        ),
    ]
