# Generated by Django 6.1 on 2026-09-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0031_offer_city_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceseason',
            name='recurring_months',
            field=models.JSONField(blank=True, default=list, help_text='Months 1–12, repeated every year. Empty: use the date interval.'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='included_driver_count',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='subagent_pricing_method',
            field=models.CharField(choices=[('UNAVAILABLE', 'Не работает с сабагентами'), ('STANDARD', 'Обычный ценник'), ('DEDICATED', 'Отдельный ценник субагента'), ('PERCENT_TOTAL', 'Процент к общей сумме')], default='STANDARD', max_length=20, verbose_name='Расчёт для субагента'),
        ),
    ]
