# Generated by Django 6.1 on 2026-09-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0032_priceseason_recurring_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='calculation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='included_benefits',
            field=models.JSONField(blank=True, default=None, help_text='Included customer benefits. Null uses the existing standard package; [] adds none.', null=True),
        ),
    ]
