# Generated by Django 6.1 on 2026-10-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0033_supplier_calculation_note_supplier_included_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityservicerule',
            name='supports_pickup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cityservicerule',
            name='supports_return',
            field=models.BooleanField(default=True),
        ),
    ]
