# Generated by Django 6.1 on 2026-10-01 16:17

import config.email_addresses
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0034_cityservicerule_supports_pickup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='booking_email',
            field=models.CharField(blank=True, help_text='Один или несколько email через ; — письмо получат все адресаты.', max_length=1000, validators=[config.email_addresses.validate_email_addresses]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='changes_email',
            field=models.CharField(blank=True, help_text='Email для изменений через ;. Если пусто, используются адреса для заказов.', max_length=1000, validators=[config.email_addresses.validate_email_addresses]),
        ),
    ]
