# Generated by Django 6.1 on 2026-10-01 16:21

import config.email_addresses
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0035_alter_supplier_booking_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='settlement_email',
            field=models.CharField(blank=True, help_text='Один или несколько email для расчётов через точку с запятой (;).', max_length=1000, validators=[config.email_addresses.validate_email_addresses]),
        ),
    ]
