# Generated by Django 6.1 on 2026-10-01 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0036_alter_supplier_settlement_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='customer_conditions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='supplier',
            name='minimum_driver_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='minimum_license_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierlocation',
            name='localized_service_instructions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vehiclegroup',
            name='excess_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
