# Generated by Django 6.1 on 2026-10-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0037_supplier_customer_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='offer_badges',
            field=models.JSONField(blank=True, default=dict, help_text='Короткие отметки в оферте по языкам: Hebrew, Russian, English.'),
        ),
    ]
