# Generated by Django 6.1 on 2026-09-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя / компания')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Субагент',
                'verbose_name_plural': 'Субагенты',
                'ordering': ['name'],
            },
        ),
    ]
