# Generated by Django 6.1 on 2026-09-23 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_subagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subagent',
            name='code_prefix',
            field=models.CharField(help_text='Две заглавные латинские буквы, например AB123456.', max_length=2, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Введите ровно две заглавные латинские буквы.')], verbose_name='Код из двух букв'),
        ),
    ]
