"""Initial Polish wording, copied into editable database templates."""
PRESENTATION = {
    "default_subject": "Oferta wynajmu samochodu w Polsce",
    "partner_fallback": "naszych partnerskich wypożyczalni samochodów",
    "labels": dict(offer="Oferta", rental_details="Szczegóły wynajmu", pickup="Odbiór samochodu", return_="Zwrot samochodu", days="Liczba dni wynajmu", options="Proponowane samochody", similar="lub podobny", total="Cena całkowita", deposit="Kaucja", missing="do ustalenia", included="Cena obejmuje", excluded="Dodatkowe usługi niewliczone w cenę", no_extras="Brak dodatkowych usług.", seats="Foteliki dziecięce i podstawki"),
    "services": {"AIRPORT":"Lotnisko", "ADDRESS":"Dostawa pod adres", "CITY_BRANCH":"Oddział w mieście"},
    "child_seat":"Jeśli potrzebny jest fotelik lub podstawka, prosimy podać wiek, wzrost i wagę każdego dziecka.",
    "child_seat_guides":"Prosimy zapoznać się z załączonymi instrukcjami wypożyczalni.",
    "child_seat_one_rent":"Dla One Rent prosimy również podać numer typu fotelika (1–5) z załącznika.",
    "airport": {"DESK":"Odbiór samochodu przy stanowisku wypożyczalni na lotnisku.", "MEET":"Przedstawiciel wypożyczalni spotka się z Państwem na lotnisku.", "UNKNOWN":"Szczegóły odbioru na lotnisku przekażemy przy potwierdzeniu rezerwacji.", "RETURN_DESK":"Zwrot samochodu w punkcie wypożyczalni na lotnisku.", "RETURN_MEET":"Przedstawiciel wypożyczalni uzgodni z Państwem zwrot na lotnisku.", "RETURN_UNKNOWN":"Szczegóły zwrotu na lotnisku przekażemy przy potwierdzeniu rezerwacji."},
    "translations": {
        "מחיר השכרת הרכב":"Wynajem samochodu", "מע״מ (VAT)":"VAT", "ביטוח מלא עם ביטול השתתפות עצמית":"Pełne ubezpieczenie bez udziału własnego", "קילומטראז׳ ללא הגבלה":"Nielimitowany przebieg", "נהג שני ללא תשלום":"Drugi kierowca bezpłatnie", "נהג נוסף":"Dodatkowy kierowca", "תוספת שירות בשדה התעופה":"Opłata lotniskowa", "כיסא תינוק / בוסטר":"Fotelik dziecięcy / podstawka", "מסירה או החזרה בכתובת בעיר":"Dostawa lub zwrot pod adresem w mieście", "מסירה והחזרה בעיר או בשדה התעופה":"Dostawa i zwrot w mieście lub na lotnisku", "אישור והרחבת כיסוי ליציאה מפולין":"Zgoda i rozszerzenie ochrony na wyjazd poza Polskę", "GPS / מערכת ניווט":"Nawigacja GPS", "שרשראות שלג":"Łańcuchy śniegowe", "נתב Wi-Fi":"Router Wi-Fi", " ליום":" za dzień", " להשכרה":" za wynajem", " ליחידה":" za sztukę", "מקסימום":"maksymalnie", "נפח תא מטען משוער: לפחות":"Szacunkowa pojemność bagażnika: co najmniej", "קיבולת תא מטען משוערת:":"Szacunkowa pojemność bagażnika:", "מזוודות גדולות":"duże walizki", "מזוודות קטנות":"małe walizki", "ליטר":"litrów", "כתובת המלון שלכם":"Adres Państwa hotelu", "כתובת המלון":"Adres hotelu", "בנזין":"Benzyna", "דיזל":"Diesel", "היברידי":"Hybryda", "חשמלי":"Elektryczny", "Automatic":"Automatyczna skrzynia biegów", "Manual":"Manualna skrzynia biegów", "Estate / Wagon":"Kombi", "Hatchback":"Hatchback", "Sedan":"Sedan", "Minivan":"Minivan", "Van":"Van", "Young driver below 24":"Młody kierowca poniżej 24 lat", "Young driver age 21-24":"Młody kierowca w wieku 21–24 lat", "Young driver":"Młody kierowca", "מסירה או החזרה מחוץ לשעות הפעילות":"Odbiór lub zwrot poza godzinami pracy", "מסירת הרכב או החזרתו בעיר מחוץ לפולין":"Odbiór lub zwrot w mieście poza Polską", "החזרת הרכב בעיר מחוץ לפולין":"Zwrot samochodu w mieście poza Polską", "Delivery or return in selected foreign city":"Dostawa lub zwrot w wybranym mieście za granicą", "התחייבות לרכב עד גיל שנתיים":"Gwarancja: samochód nie starszy niż 2 lata",
    },
}
PRESENTATION['labels']['return'] = PRESENTATION['labels'].pop('return_')
BLOCKS = [
 (10,"GREETING","","Dzień dobry,\nDziękuję za kontakt. Jestem autoryzowanym agentem wypożyczalni {suppliers}. Przygotowałem poniższe propozycje zgodnie z Państwa zapytaniem.\nProszę przeczytać ofertę do końca — poniżej znajdują się informacje potrzebne do rezerwacji."),
 (20,"IMPORTANT","Ważne informacje","Proszę zgłosić, jeśli którykolwiek kierowca ma mniej niż 24 lata lub posiada prawo jazdy krócej niż rok. Wymagania zależą od wypożyczalni.\nGwarantowana jest grupa pojazdu, a nie konkretny model. Podane modele są przykładowe.\nCena i dostępność mogą się zmienić do czasu potwierdzenia rezerwacji."),
 (30,"CROSS_BORDER","Wyjazd poza Polskę","Proszę wcześniej zgłosić planowany wyjazd poza Polskę i podać wszystkie kraje podróży. Wyjazd wymaga zgody wypożyczalni i odpowiedniego rozszerzenia ochrony. Dozwolone kraje, warunki i cena zależą od wypożyczalni."),
 (40,"PAYMENT_DEPOSIT","Kaucja","Kaucja to kwota blokowana na karcie kredytowej jako zabezpieczenie warunków wynajmu. Pełne ubezpieczenie bez udziału własnego nie znosi kaucji. Jej wysokość i warunki zwolnienia zależą od wypożyczalni i grupy pojazdu."),
 (45,"PAYMENT","Płatność","Płatność za wynajem następuje kartą kredytową przy odbiorze samochodu, wraz z blokadą kaucji. Płatność gotówką nie jest dostępna. Odbiór poza Polską lub w miejscu bez oddziału wypożyczalni może wymagać przedpłaty. Warunki przekażemy przed potwierdzeniem rezerwacji."),
 (50,"BOOKING_PROCESS","Przebieg rezerwacji","Po wyborze oferty i przesłaniu wymaganych danych przekażę zgłoszenie wypożyczalni. Zwykle w ciągu jednego dnia roboczego otrzymają Państwo oficjalny voucher e-mailem. Samochód jest gwarantowany dopiero po potwierdzeniu przez wypożyczalnię. Proszę sprawdzić voucher i zachować go do odbioru samochodu."),
 (60,"CANCELLATION","Anulowanie","Anulowanie rezerwacji jest bezpłatne. Proszę poinformować mnie jak najwcześniej, najlepiej kilka dni wcześniej. Nieodebranie samochodu bez wcześniejszego anulowania wiąże się z opłatą 200 PLN."),
 (65,"CHANGES","Zmiany rezerwacji","Proszę przesłać wszystkie zmiany razem, jak najwcześniej, podając numer rezerwacji z vouchera. Warto sprawdzić rezerwację około dwóch tygodni przed podróżą. Każda zmiana wymaga zgody wypożyczalni i może wpłynąć na cenę oraz dostępność. Po zatwierdzeniu otrzymają Państwo zaktualizowany voucher."),
 (70,"DURING_RENTAL","Podczas wynajmu","W razie pytań lub problemów proszę najpierw skontaktować się z obsługą wypożyczalni, korzystając z danych na voucherze i podając numer rezerwacji. Pomagam w wyjątkowych sytuacjach, ale nie zapewniam całodobowej obsługi."),
 (75,"TOLLS","Opłaty drogowe","Opłaty drogowe w Polsce i innych krajach nie są wliczone w cenę wynajmu. Kierowca odpowiada za sprawdzenie i opłacenie wymaganych opłat na trasie. Zgoda na wyjazd za granicę i rozszerzenie ochrony nie obejmują opłat drogowych ani winiet."),
 (80,"ORDER_DETAILS","Dane potrzebne do rezerwacji","Proszę odpowiedzieć na ten e-mail i podać:\n• numer oferty i wybraną grupę samochodu;\n• imiona i nazwiska wszystkich kierowców alfabetem łacińskim, zgodnie z prawem jazdy;\n• numer telefonu dostępny podczas pobytu w Polsce;\n• numer lotu przy odbiorze na lotnisku lub nazwę i adres hotelu przy dostawie do hotelu;\n• pełny adres zamieszkania z kodem pocztowym, alfabetem łacińskim.\nProszę również zgłosić kierowców poniżej 24 lat lub z prawem jazdy krócej niż rok oraz planowany wyjazd poza Polskę."),
 (85,"DRIVING_DOCUMENTS","Dokumenty przy odbiorze","Przy odbiorze każdy kierowca musi okazać ważne, oryginalne prawo jazdy w formie plastikowej karty. Zalecane jest również międzynarodowe prawo jazdy, szczególnie przy podróży poza Polskę. Zależnie od kraju wydania dokumentu, krajów podróży i warunków wypożyczalni może być ono wymagane. Nie zastępuje oryginału — należy mieć oba dokumenty."),
 (90,"USEFUL_LINKS","Przydatne linki",""),
 (95,"AI_NOTE","Krótka informacja","Oferta została przygotowana z pomocą AI, ale pozostajemy do Państwa dyspozycji. W razie pytań lub potrzeby poprawienia informacji proszę odpowiedzieć na ten e-mail — odpowiemy osobiście."),
 (100,"SIGNATURE","","Pozdrawiam,\nIdan Rats\nTelefon / WhatsApp: +48 533 100 636\nPreferowany kontakt e-mail:\nidanrentacar@gmail.com\nidan.caliber@gmail.com\nhttps://poland-rent-car.com/\nhttps://trip2poland.co.il/\nhttps://travel-time.co.il/"),
]
