"""Editable English wording for customer offers."""

BLOCKS = [
    (10, "GREETING", "", "Hello,\nThank you for contacting us. I am an authorised agent for {suppliers}. I prepared the following rental options according to your request.\nPlease read the offer to the end. The details needed to make a booking are listed below."),
    (20, "IMPORTANT", "Important information", "Please tell us in advance if any driver is under 24 or has held a driving licence for less than one year. Requirements vary between rental companies.\nThe rental company guarantees a vehicle group, not a specific model. Models shown are examples.\nPrice and availability may change until the booking is confirmed."),
    (30, "CROSS_BORDER", "Travel outside Poland", "Please tell us in advance if you plan to leave Poland and list all destination countries. Cross-border travel requires prior approval and suitable coverage. Permitted countries, conditions and prices depend on the rental company."),
    (40, "PAYMENT_DEPOSIT", "Deposit", "The deposit is an amount blocked on the credit card as security for the rental conditions. Full insurance with zero excess does not remove the deposit requirement. The amount and release conditions depend on the rental company and vehicle group."),
    (45, "PAYMENT", "Payment", "Rental payment is made by credit card when collecting the vehicle, together with the deposit block. Cash payment is not available. Prepayment may be required for collection outside Poland or where the rental company has no branch. We will confirm such conditions before booking."),
    (50, "BOOKING_PROCESS", "Booking process", "After you choose an option and send the required details, I will forward the request to the rental company. You will normally receive an official voucher by email within one business day. The vehicle is guaranteed only after the rental company confirms the booking. Please check the voucher and keep it available when collecting the vehicle."),
    (60, "CANCELLATION", "Cancellation", "Cancellation is free of charge. Please notify me as early as possible, preferably several days in advance. If the vehicle is not collected and no cancellation notice was given, a charge of 200 PLN will apply."),
    (65, "CHANGES", "Booking changes", "Please send all requested changes together and as early as possible. Include the booking number shown on the voucher. We recommend checking the booking about two weeks before travel. Every change requires rental company approval and may affect price and availability. An updated voucher will be sent after approval."),
    (70, "DURING_RENTAL", "During the rental", "For questions, problems or assistance during the rental, first contact the rental company's customer service using the details on the voucher and provide the booking number. I remain available for exceptional cases, but I do not provide round-the-clock support."),
    (75, "TOLLS", "Toll roads", "Road tolls are not included in Poland or other countries. The driver must check and pay the tolls required for the planned route. Cross-border approval and insurance coverage do not include tolls or motorway stickers."),
    (80, "ORDER_DETAILS", "Details needed to book", "Please reply to this email with:\n• the offer number and selected vehicle group;\n• every driver's full name in English, exactly as shown on the driving licence;\n• a telephone number available during the stay in Poland;\n• the flight number for airport collection, or hotel name and address for hotel delivery;\n• the full home address, including postal code, in English.\nPlease also state whether any driver is under 24 or has held a licence for less than one year, and whether travel outside Poland is planned."),
    (85, "DRIVING_DOCUMENTS", "Documents required", "When collecting the vehicle, every driver must present a valid original driving licence in plastic card form. An international driving permit is also recommended, especially for travel to other EU countries. Depending on the issuing country, destinations and rental company conditions, it may be mandatory. It does not replace the original licence; both must be carried together."),
    (90, "USEFUL_LINKS", "Useful links", ""),
    (95, "AI_NOTE", "A quick note from us", "This offer was prepared with the help of AI, but we are still in the driver's seat. If you have a question or need anything corrected or clarified, simply reply to this email and one of us will answer personally."),
    (100, "SIGNATURE", "", "Kind regards,\nIdan Rats\nPhone / WhatsApp: +48 533 100 636\nEmail is preferred:\nidanrentacar@gmail.com\nidan.caliber@gmail.com\nhttps://poland-rent-car.com/\nhttps://trip2poland.co.il/\nhttps://travel-time.co.il/"),
]
