# Generated by Django 6.1 on 2026-10-08 19:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0019_alter_supplieremaildelivery_recipient'),
        ('employees', '0003_subagent_code_prefix'),
        ('suppliers', '0038_supplier_offer_badges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Месяц (первое число)')),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('4'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Комиссия работника (%)')),
                ('vat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='НДС для перевода брутто в нетто (%)')),
                ('state', models.CharField(choices=[('DRAFT', 'В работе'), ('CLOSED', 'Сверено')], default='DRAFT', max_length=12, verbose_name='Сверка')),
                ('invoice_number', models.CharField(blank=True, max_length=120, verbose_name='Номер фактуры')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Дата фактуры')),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма фактуры, PLN (не оборот аренды)')),
                ('received', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Получено от поставщика, PLN')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Дата получения последнего платежа')),
                ('employee_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Выплачено работнику, PLN')),
                ('employee_paid_date', models.DateField(blank=True, null=True, verbose_name='Дата выплаты работнику')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Работник')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier', verbose_name='Фирма')),
            ],
            options={
                'verbose_name': 'Сверка за месяц',
                'verbose_name_plural': 'Сверки за месяц',
                'ordering': ['-month', 'supplier'],
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(max_length=150)),
                ('reason', models.CharField(max_length=255)),
                ('snapshot', models.JSONField()),
                ('excel', models.BinaryField()),
                ('digest', models.CharField(max_length=64)),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='reconciliation.reconciliation')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('own', models.JSONField(blank=True, default=dict)),
                ('supplier_lines', models.JSONField(blank=True, default=list)),
                ('employee_data', models.JSONField(blank=True, default=dict)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('decision', models.CharField(choices=[('REVIEW', 'Проверить'), ('INCLUDE', 'Включить'), ('CANCEL', 'Отмена'), ('CARRY', 'Следующий месяц'), ('EXCLUDE', 'Не входит в этот месяц')], default='REVIEW', max_length=12)),
                ('note', models.TextField(blank=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bookings.booking')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='reconciliation.reconciliation')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('OWN', 'Мои записи'), ('SUPPLIER', 'Отчёт поставщика'), ('EMPLOYEE', 'Список работника')], max_length=12)),
                ('name', models.CharField(max_length=255)),
                ('digest', models.CharField(max_length=64)),
                ('mapping', models.JSONField(default=dict)),
                ('content', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to='reconciliation.reconciliation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reconciliation',
            constraint=models.UniqueConstraint(fields=('month', 'supplier'), name='unique_supplier_month_reconciliation'),
        ),
        migrations.AddConstraint(
            model_name='row',
            constraint=models.UniqueConstraint(fields=('reconciliation', 'number'), name='unique_reconciliation_reservation'),
        ),
        migrations.AddConstraint(
            model_name='upload',
            constraint=models.UniqueConstraint(fields=('reconciliation', 'kind', 'digest'), name='unique_reconciliation_file'),
        ),
    ]
