# Generated by Django 6.1 on 2026-10-09 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliation',
            name='direct_orderer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заказывающий для прямых заказов'),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='direct_prefixes',
            field=models.CharField(blank=True, max_length=100, verbose_name='Префиксы прямых заказов через запятую'),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='direct_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Моя комиссия за прямые заказы (%)'),
        ),
        migrations.AlterField(
            model_name='row',
            name='decision',
            field=models.CharField(choices=[('REVIEW', 'Проверить'), ('INCLUDE', 'Включить'), ('DIRECT', 'Прямой заказ поставщика'), ('CANCEL', 'Отмена'), ('CARRY', 'Следующий месяц'), ('EXCLUDE', 'Не входит в этот месяц')], default='REVIEW', max_length=12),
        ),
    ]
