# Generated by Django 6.1 on 2026-10-10 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0002_reconciliation_direct_orderer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='own_excel',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='row',
            name='previous_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='later_rows', to='reconciliation.row'),
        ),
        migrations.AlterField(
            model_name='row',
            name='decision',
            field=models.CharField(choices=[('PREVIOUS', 'Учтён ранее'), ('REVIEW', 'Проверить'), ('INCLUDE', 'Включить'), ('DIRECT', 'Прямой заказ поставщика'), ('CANCEL', 'Отмена'), ('CARRY', 'Следующий месяц'), ('EXCLUDE', 'Не входит в этот месяц')], default='REVIEW', max_length=12),
        ),
    ]
