# Generated by Django 6.1 on 2026-08-27 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('suppliers', '0007_add_vehicle_groups_and_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name_latin', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_1', models.CharField(max_length=30)),
                ('phone_2', models.CharField(blank=True, max_length=30)),
                ('phone_3', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('preferred_language', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=20)),
                ('warning_level', models.CharField(choices=[('NONE', 'None'), ('INFO', 'Information'), ('WARNING', 'Warning'), ('SERIOUS', 'Serious')], default='NONE', max_length=20)),
                ('warning_text', models.TextField(blank=True)),
                ('internal_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to='employees.employee')),
                ('preferred_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_customers', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CANCELLATION', 'Cancellation'), ('REFUSAL', 'Refusal'), ('NO_SHOW', 'No-show'), ('ACCIDENT', 'Accident'), ('DAMAGE', 'Damage'), ('COMPLAINT', 'Complaint'), ('PAYMENT_ISSUE', 'Payment issue'), ('LATE_RETURN', 'Late return'), ('DISPUTE', 'Dispute'), ('SUPPLIER_PREFERENCE', 'Supplier preference'), ('POSITIVE_NOTE', 'Positive note'), ('MANUAL_WARNING', 'Manual warning'), ('OTHER', 'Other')], max_length=30)),
                ('event_date', models.DateField()),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='INFO', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_warning', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_events', to='employees.employee')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='customers.customer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_events', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
