# Generated by Django 6.1 on 2026-08-27 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_pickup_datetime_booking_rental_days_and_more'),
        ('suppliers', '0010_supplierextra_is_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='flight_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_bookings', to='suppliers.supplierlocation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_location_text',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_bookings', to='suppliers.supplierlocation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_location_text',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='suppliers.vehiclegroup'),
        ),
    ]
