# Generated by Django 6.1 on 2026-08-27 18:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_flight_number_booking_hotel_name_and_more'),
        ('suppliers', '0011_pricelist_pricedayrange_priceseason_vehiclerate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='calculated_vehicle_price_gross',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='currency',
            field=models.CharField(default='PLN', max_length=3),
        ),
        migrations.AddField(
            model_name='booking',
            name='extras_total_gross',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='manual_price_override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='manual_vehicle_price_gross',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional manual customer price including VAT.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='booking',
            name='price_calculation_status',
            field=models.CharField(choices=[('NOT_CALCULATED', 'Not calculated'), ('CALCULATED', 'Calculated'), ('NO_RATE', 'No matching rate'), ('OVERRIDDEN', 'Manually overridden')], default='NOT_CALCULATED', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='price_day_range_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='booking',
            name='price_list_version_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='price_season_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price_gross',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_daily_rate_gross_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_price_gross',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_rate',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_snapshots', to='suppliers.vehiclerate'),
        ),
        migrations.CreateModel(
            name='BookingExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('customer_visible_name', models.CharField(max_length=150)),
                ('supplier_visible_name', models.CharField(max_length=150)),
                ('calculation_type_snapshot', models.CharField(max_length=20)),
                ('unit_price_gross_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculated_price_gross', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency_snapshot', models.CharField(max_length=3)),
                ('formula_snapshot', models.JSONField(blank=True, default=dict)),
                ('is_mandatory_snapshot', models.BooleanField(default=False)),
                ('included_in_total', models.BooleanField(default=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='bookings.booking')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_entries', to='suppliers.supplierextra')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_entries', to='suppliers.supplierextrarate')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('booking', 'extra'), name='one_extra_type_per_booking')],
            },
        ),
    ]
