# Generated by Django 6.1 on 2026-08-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_calculated_vehicle_price_gross_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingextra',
            name='maximum_amount_gross_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bookingextra',
            name='minimum_amount_gross_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
