# Generated by Django 6.1 on 2026-08-27 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bookingextra_maximum_amount_gross_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingextra',
            name='actual_cost_gross',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='bookingextra',
            name='calculation_complete',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='bookingextra',
            name='calculation_warning',
            field=models.CharField(blank=True, editable=False, max_length=250),
        ),
        migrations.AddField(
            model_name='bookingextra',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='bookingextra',
            name='formula_units',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Special units used by a formula, for example missing fuel litres.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
