# Generated by Django 6.1 on 2026-08-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_bookingextra_actual_cost_gross_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_address_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_city_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_country_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_email_snapshot',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_name_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_phone_1_snapshot',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_phone_2_snapshot',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_phone_3_snapshot',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_postal_code_snapshot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='invoice_address_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='invoice_city_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='invoice_country_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='invoice_email_snapshot',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='invoice_name_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='invoice_postal_code_snapshot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='invoice_tax_id_snapshot',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='wants_invoice_snapshot',
            field=models.BooleanField(default=False),
        ),
    ]
