# Generated by Django 6.1 on 2026-08-27 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_customer_address_snapshot_and_more'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_by_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='booking',
            name='salesperson_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_bookings', to='employees.employee'),
        ),
        migrations.CreateModel(
            name='BookingHistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('STATUS_CHANGED', 'Status changed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No-show'), ('DETAILS_CHANGED', 'Details changed'), ('PRICE_OVERRIDE', 'Price overridden'), ('DRIVER_CHANGED', 'Driver changed'), ('EXTRA_CHANGED', 'Extra changed'), ('NOTE', 'Note')], max_length=30)),
                ('description', models.TextField()),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('old_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='bookings.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_history_events', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
