# Generated by Django 6.1 on 2026-09-14 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_created_by_employee_and_more'),
        ('quotes', '0013_preserve_previous_deliveries'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='source_quote',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_booking', to='quotes.quote'),
        ),
        migrations.AddField(
            model_name='booking',
            name='source_quote_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
