# Generated by Django 6.1 on 2026-09-18 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_source_quote_booking_source_quote_snapshot'),
        ('employees', '0002_subagent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_by_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='manual_entry_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='order_source',
            field=models.CharField(choices=[('SELF', 'Мой заказ'), ('EMPLOYEE', 'Заказ сотрудника'), ('SUBAGENT', 'Заказ субагента')], default='SELF', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='sub_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.subagent'),
        ),
    ]
