# Generated by Django 6.1 on 2026-09-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_bookingvoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='return_hotel_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
