# Generated by Django 6.1 on 2026-09-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_booking_return_hotel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='manual_adjustment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='manual_adjustment_label',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
