# Generated by Django 6.1 on 2026-09-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_booking_manual_adjustment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='child_seat_details',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
