# Generated by Django 6.1 on 2026-09-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_booking_child_seat_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='subagent_price_adjustment_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
