# Generated by Django 6.1 on 2026-10-01 16:17

import config.email_addresses
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_allow_multiple_bookings_per_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieremaildelivery',
            name='recipient',
            field=models.CharField(max_length=1000, validators=[config.email_addresses.validate_email_addresses]),
        ),
    ]
