# Generated by Django 6.1 on 2026-09-13 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_quote_email_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='email_subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quoteoption',
            name='customer_comment',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='QuoteEmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=250)),
                ('html', models.TextField()),
                ('attachments', models.JSONField(default=list)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_deliveries', to='quotes.quote')),
            ],
            options={
                'ordering': ['-sent_at', '-pk'],
            },
        ),
    ]
