# Generated by Django 6.1 on 2026-09-20 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_preserve_previous_deliveries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='sent_by_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quoteemaildelivery',
            name='sent_by_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_email_deliveries', to=settings.AUTH_USER_MODEL),
        ),
    ]
