# Generated by Django 6.1 on 2026-09-23 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_subagent_code_prefix'),
        ('quotes', '0017_english_offer_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='sub_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='employees.subagent'),
        ),
    ]
